spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 67d9c785db77fb53b745
            clientSecret: 445f7086212066df12627b265202e45df12ea857

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

server:
  port: 8080